version: "3.8"
services:
  nop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nop
    networks:
    - nopnet
    ports:
    - "34567:5000"
    depends_on:
    - nopdb

  nopdb:
    image: mysql:8
    networks:
      - nopnet
    volumes:
      - "nop-db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=nop
      - MYSQL_PASSWORD=rootroot
      - MYSQL_DATABASE=nop
    container_name: nopdb
    ports:
      - 3306
volumes:
  nop-db:
networks:
  public:
  private:
  nopnet:

