version: "3.8"
services:
  student:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student
    ports:
      - "34567:8080"
    depends_on:
      - mysqlserver
  
  mysqlserver:
    image: mysql:8
    volumes:
      - "mysqlserver:/var/lib/mysql"
    environment:
      - MYSQL_USERNAME='directdevops'
      - MYSQL_PASSWORD='directdevops'
      - MYSQL_SERVER='localhost'
      - MYSQL_SERVER_PORT='3306'
      - MYSQL_DATABASE='test'
    container_name: mysqlserver
    ports:
      - 3306
volumes:
  mysqlserver:
      
