---
version: "3.8"

services:
  spc: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - spc-net 
networks:
  spc-net:

https://github.com/dummyrepos/spring-petclinic-docker/commit/07b4df09a80ee0f020219ddfe22e82653068d23a